@startuml Hotel Delete

header Sameple Hotel Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Hotel (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hotels" as routerHotels
participant "<<controllers>>\n:hotels" as controllersHotels
participant "<<model>>\n:Hotel" as modelHotel
database "<<MongoDB>>\n:hotels" as HotelsDatabase

client->server++:req.delete('/api/v1/hotels/:id')
server->routerHotels++:app.use('/api/v1/hotels',hotels)
routerHotels->controllersHotels++:deleteHotel
controllersHotels->modelHotel ++:findById(req.params.id)\nHotel.deleteOne({_id:req.params.id})
modelHotel ->HotelsDatabase ++: HotelSchema
HotelsDatabase --> modelHotel --: {}
controllersHotels <-- modelHotel --:{}
controllersHotels->client --:response

@enduml