@startuml Register

header Sample Hotel Authentication Sequence Diagram
footer Page %page% of %lastpage%
title "User Registration"

participant "Client" as client
participant "<<JavaScript>>\n:Server" as server
participant "<<Router>>\n:auth" as routerAuth
participant "<<Controllers>>\n:auth" as controllerAuth
participant "<<Model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UsersDatabase

client -> server++: req.post('/api/v1/auth/register')
server -> routerAuth++: app.use('/api/v1/auth', authRoutes)
routerAuth -> controllerAuth++: register(req, res)
controllerAuth -> modelUser ++: create(req.body)
modelUser -> UsersDatabase ++: Insert new user data
UsersDatabase --> modelUser --: Created user data
controllerAuth -> controllerAuth: Generate JWT token
controllerAuth -> client --: Response with token

@enduml
