@startuml Hotel Booking System Use Case Diagram

left to right direction

actor "Unregistered User" as unregisteredUser
actor "Registered User" as registeredUser
actor "Admin" as admin

rectangle "Hotel Booking System" {
  top to bottom direction
  usecase "Register" as register
  usecase "Login" as login
  usecase "View Hotels" as view
  usecase "Manage Booking" as manageBooking
  usecase "Manage Hotel" as manageHotel
  usecase "Logout" as logout
}

left to right direction

unregisteredUser -- register
unregisteredUser -- login
unregisteredUser -- view

registeredUser -- login
registeredUser -- view
registeredUser -- logout
registeredUser -- manageBooking

login -- admin
logout -- admin
view -- admin
manageBooking -- admin
manageHotel -- admin

@enduml